spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: SecureApplication
  security:
    jwt:
      secret-key: adsfasdfasdf
      expiration-time: 8568768678
